export const CardData = [
  {
    id: 0,
    title: "Total Sales",
    price: "$3,459",
    percentage: "2.11%",
    graph: "Up",
    month: "Vs last month",
  },
  {
    id: 1,
    title: "Total Orders",
    price: "34K",
    percentage: "2.11%",
    graph: "Up",
    month: "Vs last month",
  },
  {
    id: 2,
    title: "Total Pax",
    price: "345.8K",
    percentage: "2.11%",
    graph: "Up",
    month: "Vs last month",
  },
  {
    id: 3,
    title: "Total Sales",
    price: "$4,598",
    percentage: "2.11%",
    graph: "Down",
    month: "Vs last month",
  },
  {
    id: 4,
    title: "Average Order value",
    price: "$67.00",
    percentage: "2.11%",
    graph: "Down",
    month: "Vs last month",
  },
  {
    id: 5,
    title: "Commission Paid",
    price: "$2,980",
    percentage: "2.11%",
    graph: "Up",
    month: "Vs last month",
  },
  {
    id: 6,
    title: "Lead Times",
    price: "56 Days",
    percentage: "2.11%",
    graph: "Up",
    month: "Vs last month",
  },
];

export const BlockData = [
  {
    id: 1,
    title: "Invoice Raises",
    price: "$6,598%",
    percentage: "2.11%",
    graph: "Up",
    month: "Vs last month",
  },
  {
    id: 2,
    title: "Invoice Paid",
    price: "$6,598%",
    percentage: "2.11%",
    graph: "Up",
    month: "Vs last month",
  },
  {
    id: 3,
    title: "Invoice Due",
    price: "$6,598%",
    percentage: "2.11%",
    graph: "Down",
    month: "Vs last month",
  },
  {
    id: 3,
    title: "Forward Bookings",
    price: "$6,598%",
    percentage: "2.11%",
    graph: "Down",
    month: "Vs last month",
  },
];

export const Data = [
  {
    country: "AD",
    "hot dog": 51,
    "hot dogColor": "hsl(160, 70%, 50%)",
    burger: 77,
    burgerColor: "hsl(240, 70%, 50%)",
    sandwich: 47,
    sandwichColor: "hsl(206, 70%, 50%)",
    kebab: 35,
    kebabColor: "hsl(130, 70%, 50%)",
    fries: 4,
    friesColor: "hsl(16, 70%, 50%)",
    donut: 64,
    donutColor: "hsl(218, 70%, 50%)",
  },
  {
    country: "AE",
    "hot dog": 116,
    "hot dogColor": "hsl(255, 70%, 50%)",
    burger: 187,
    burgerColor: "hsl(160, 70%, 50%)",
    sandwich: 15,
    sandwichColor: "hsl(225, 70%, 50%)",
    kebab: 188,
    kebabColor: "hsl(277, 70%, 50%)",
    fries: 160,
    friesColor: "hsl(333, 70%, 50%)",
    donut: 37,
    donutColor: "hsl(15, 70%, 50%)",
  },
  {
    country: "AF",
    "hot dog": 168,
    "hot dogColor": "hsl(218, 70%, 50%)",
    burger: 182,
    burgerColor: "hsl(157, 70%, 50%)",
    sandwich: 198,
    sandwichColor: "hsl(221, 70%, 50%)",
    kebab: 177,
    kebabColor: "hsl(177, 70%, 50%)",
    fries: 97,
    friesColor: "hsl(84, 70%, 50%)",
    donut: 49,
    donutColor: "hsl(286, 70%, 50%)",
  },
  {
    country: "AG",
    "hot dog": 59,
    "hot dogColor": "hsl(348, 70%, 50%)",
    burger: 176,
    burgerColor: "hsl(221, 70%, 50%)",
    sandwich: 102,
    sandwichColor: "hsl(296, 70%, 50%)",
    kebab: 176,
    kebabColor: "hsl(296, 70%, 50%)",
    fries: 186,
    friesColor: "hsl(15, 70%, 50%)",
    donut: 170,
    donutColor: "hsl(44, 70%, 50%)",
  },
  {
    country: "AI",
    "hot dog": 105,
    "hot dogColor": "hsl(139, 70%, 50%)",
    burger: 195,
    burgerColor: "hsl(346, 70%, 50%)",
    sandwich: 43,
    sandwichColor: "hsl(308, 70%, 50%)",
    kebab: 192,
    kebabColor: "hsl(79, 70%, 50%)",
    fries: 22,
    friesColor: "hsl(115, 70%, 50%)",
    donut: 36,
    donutColor: "hsl(286, 70%, 50%)",
  },
  {
    country: "AL",
    "hot dog": 75,
    "hot dogColor": "hsl(36, 70%, 50%)",
    burger: 192,
    burgerColor: "hsl(296, 70%, 50%)",
    sandwich: 182,
    sandwichColor: "hsl(321, 70%, 50%)",
    kebab: 30,
    kebabColor: "hsl(11, 70%, 50%)",
    fries: 8,
    friesColor: "hsl(192, 70%, 50%)",
    donut: 180,
    donutColor: "hsl(206, 70%, 50%)",
  },
  {
    country: "AM",
    "hot dog": 132,
    "hot dogColor": "hsl(322, 70%, 50%)",
    burger: 28,
    burgerColor: "hsl(241, 70%, 50%)",
    sandwich: 184,
    sandwichColor: "hsl(84, 70%, 50%)",
    kebab: 117,
    kebabColor: "hsl(310, 70%, 50%)",
    fries: 116,
    friesColor: "hsl(322, 70%, 50%)",
    donut: 44,
    donutColor: "hsl(202, 70%, 50%)",
  },
];

export const TableboardData = [
  {
    id: 1,
    name: " Milford Sound Cruise",
    sales: "$65,000",
    orders: "675",
    addiRevenue: "$32,080",
    totalPax: "12,000",
    avgOrderValue: "$32,080",
    commissionsPaid: "$32.080",
    leadTime: "2 Days",
    reseller: "80%",
    direct: "20%",
    image: "toy-4.png",
    icon: "Frame-1.svg",
    img: "Frame-2.svg",
  },
  {
    id: 2,
    name: " Milford Sound Cruise fr..",
    sales: "$65,000",
    orders: "675",
    addiRevenue: "$32,080",
    totalPax: "546",
    avgOrderValue: "+$32,080",
    commissionsPaid: "$32.080",
    leadTime: "2 Days",
    reseller: "60%",
    direct: "40%",
    image: "toy-3.png",
    icon: "Frame-3.svg",
    img: "Frame-3.svg",
  },
  {
    id: 3,
    name: " Fly Cruise Fly Milford S...",
    sales: "$65,000",
    orders: "675",
    addiRevenue: "$32,080",
    totalPax: "123",
    avgOrderValue: "$32,080",
    commissionsPaid: "$32.080",
    leadTime: "2 Days",
    reseller: "90%",
    direct: "10%",
    image: "toy-2.png",
    icon: "Frame-1.svg",
    img: "Frame-2.svg",
  },
  {
    id: 4,
    name: " Kayaking in Milford So...",
    sales: "$65,000",
    orders: "675",
    addiRevenue: "$32,080",
    totalPax: "87",
    avgOrderValue: "$32,080",
    commissionsPaid: "+$32.080",
    leadTime: "2 Days",
    reseller: "75%",
    direct: "25%",
    image: "toy-1.png",
    icon: "Frame-1.svg",
    img: "Frame-2.svg",
  },
  {
    id: 4,
    name: " Kayaking in Milford So...",
    sales: "$65,000",
    orders: "675",
    addiRevenue: "$32,080",
    totalPax: "23",
    avgOrderValue: "$32,080",
    commissionsPaid: "$32.080",
    leadTime: "2 Days",
    reseller: "55%",
    direct: "45%",
    image: "toy-5.png",
    icon: "Frame-3.svg",
    img: "Frame-3.svg",
  },
];

export const DataTableData = [
  {
    id: 1,
    name: " Scenic Cruise",
    sales: "$65,000",
    orders: "675",
    addiRevenue: "$32,080",
    totalPax: "12,000",
    avgOrderValue: "$32,080",
    commissionsPaid: "$32.080",
    leadTime: "2 Days",
    reseller: "80%",
    direct: "20%",
    icon: "Frame-1.svg",
    img: "Frame-2.svg",
    image: "icon-3.svg",
  },
  {
    id: 2,
    name: "Scenic Flight",
    sales: "$65,000",
    orders: "675",
    addiRevenue: "$32,080",
    totalPax: "546",
    avgOrderValue: "$32,080",
    commissionsPaid: "$32.080",
    leadTime: "2 Days",
    reseller: "60%",
    direct: "40%",
    icon: "Frame-3.svg",
    img: "Frame-3.svg",
    image: "icon-1.svg",
  },
  {
    id: 3,
    name: "Kayaking",
    sales: "$65,000",
    orders: "675",
    addiRevenue: "$32,080",
    totalPax: "123",
    avgOrderValue: "$32,080",
    commissionsPaid: "$32.080",
    leadTime: "2 Days",
    reseller: "90%",
    direct: "10%",
    icon: "Frame-1.svg",
    img: "Frame-2.svg",
    image: "icon-2.svg",
  },
  {
    id: 4,
    name: "Day Tour",
    sales: "$65,000",
    orders: "675",
    addiRevenue: "$32,080",
    totalPax: "87",
    avgOrderValue: "$32,080",
    commissionsPaid: "$32.080",
    leadTime: "2 Days",
    reseller: "75%",
    direct: "25%",
    icon: "Frame-1.svg",
    img: "Frame-2.svg",
    image: "icon-3.svg",
  },
  {
    id: 5,
    name: "Rafting",
    sales: "$65,000",
    orders: "675",
    addiRevenue: "$32,080",
    totalPax: "23",
    avgOrderValue: "$32,080",
    commissionsPaid: "$32.080",
    leadTime: "2 Days",
    reseller: "55%",
    direct: "45%",
    icon: "Frame-3.svg",
    img: "Frame-3.svg",
    image: "icon-3.svg",
  },
];

export const GraphTableData = [
  {
    id: 1,
    name: "Brazil",
    avgOrderValue: "$32,080",
    booking: "675",
    leadTime: "2 Days",
    image: "flag-5.svg",
  },
  {
    id: 2,
    name: "Canada",
    avgOrderValue: "$32,080",
    booking: "675",
    leadTime: "2 Days",
    image: "flag-1.svg",
  },
  {
    id: 3,
    name: "Colombia",
    avgOrderValue: "$32,080",
    booking: "675",
    leadTime: "2 Days",
    image: "flag-2.svg",
  },
  {
    id: 1,
    name: "Malaysia",
    avgOrderValue: "$32,080",
    booking: "675",
    leadTime: "2 Days",
    image: "flag-3.svg",
  },
  {
    id: 1,
    name: "United States of America",
    avgOrderValue: "$32,080",
    booking: "675",
    leadTime: "2 Days",
    image: "flag-4.svg",
  },
];

export const Monthdropdownlist = [
  {
    id: 1,
    name: 'This Month',
    icon: ""
  },
  {
    id: 2,
    name: 'Priveus Month',
    icon: ""
  }
]

export const Chartdropdownlist = [
  {
      id: 1,
      name: 'Bar Chart',
      icon: "/images/dashboard/bar-line-chart.svg"
  },
  {
      id: 2,
      name: 'Pie Chart',
      icon: "/images/dashboard/pie-chart-03.svg"
  },
  {
      id: 3,
      name: 'Line Chart',
      icon: "/images/dashboard/line-chart-up-01.svg"
  },
]

export const peformanceData = [
  { index: 0, title: "Trip advisor", image: "/images/dashboard/Ellipse1.svg", performance: "89%", price: '$67,098', color: 'bg-[#397CF629]' },
  { index: 1, title: "Viator", image: "/images/dashboard/Ellipse2.svg", performance: "75%", price: '$32,098', color: 'bg-[#EE46BC29]' },
  { index: 2, title: "Klook", image: "/images/dashboard/Ellipse3.svg", performance: "65%", price: '$67,098', color: 'bg-[#F7900929]' },
  { index: 3, title: "Experience Oz", image: "/images/dashboard/Ellipse4.svg", performance: "35%", price: '$67,098', color: 'bg-[#15C39A29]' },
  { index: 4, title: "GetYourGuide", image: "/images/dashboard/Ellipse5.svg", performance: "55%", price: '$67,098', color: 'bg-[#3D39F629]' },
]


export const commentsData = [
  {
      id: 0,
      user: "/images/dashboard/Oval1.svg",
      name: "Jonathan Willium",
      ratting: 4.0,
      dayago: '4 days ago',
      description: "It's user friendly. Easy to search, browse, look up orders, track shipping progress, update profile settings..."
  },
  {
      id: 1,
      user: "/images/dashboard/Oval2.svg",
      name: "John Miller",
      ratting: 5.0,
      dayago: '4 days ago',
      description: "It's user friendly. Easy to search, browse, look up orders, track shipping progress, update profile settings..."
  },
  {
      id: 2,
      user: "/images/dashboard/Oval3.svg",
      name: "Ket Jim",
      ratting: 5.0,
      dayago: '4 days ago',
      description: "It's user friendly. Easy to search, browse, look up orders, track shipping progress, update profile settings..."
  },
]